### ISSUE TITLE
Improve background image load time

### ISSUE THREAD

**Issue by thealamu** [thealamu/trim#12]
Background image on the homepage seems to be heavy. This drags the load time.

**Comment by SwiftPush** [comment]
Hi, is this still an issue, or has it been fixed by #29 ?

I guess you no longer want it, with the UI overhaul. But in case you still wanted it, here's what could be done to reduce the file size:
* Original jpg (6472x3641) - **7.7MB**
* Smaller jpg (3200x1800) - **2.0MB**
* Smaller webp (3200x1800) - **1.1MB**

Alternatively, you could still improve the file size of your other graphics (3401776.jpg)
* Original jpg (3000x2000) - **371KB**
* Full size webp (3000x2000) - **159KB**
* Smaller jpg (1200x800) - **131KB**
* Smaller webp (1200x800) - **28KB**

And you can use the `<picture>` element, which allows web browsers that don't support webp, to fallback to jpg

**Comment by thealamu** [comment]
The load time has been fixed by #29. This should have been closed, thanks :+1: !  @oforshaddy this would have actually improved the load time for the previous UI.

**Comment by thealamu** [comment]
On the other hand, I think the current graphics can gain from your suggestion. Do you mind making a pull request with the optimized image?

**Comment by thealamu** [comment]
Closing this now
